/** Regenerate docs/STAGE-COVERAGE.md from the live audit. */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

const raw = execSync('bun run scripts/audit-coverage.ts', { encoding: 'utf8' });
interface Row { slug: string; stages: number; pct: number; want: number; missing: string[]; foreign: string[] }
const rows: Row[] = [];
let cur: Row | null = null;
for (const line of raw.split('\n')) {
  const m = /^(\S+)\s+\((\d+) stages, covers (\d+)% of (\d+) features/.exec(line);
  if (m) {
    cur = { slug: m[1], stages: +m[2], pct: +m[3], want: +m[4], missing: [], foreign: [] };
    rows.push(cur);
    continue;
  }
  if (!cur) continue;
  if (line.includes('missing concepts') || line.includes('missing reference')) cur.missing.push(...line.split(':')[1].trim().split(/\s+/));
  if (line.includes('from other steps')) cur.foreign.push(...line.split(':')[1].trim().split(/\s+/));
}

const done = rows.filter((r) => r.pct === 100);
const todo = rows.filter((r) => r.pct < 100).sort((a, b) => a.pct - b.pct);

const body = `# Stage coverage

Generated by \`bun run scripts/write-tracking.ts\`. Do not hand-edit the tables.

Every lab is a run of STAGES. The rules, in the order they were learned:

1. **A stage is one real json-render feature**, never a permutation of the one
   before it. Two sides of one feature are two \`parts\` of one stage.
2. **Vocabulary is not a lesson.** \`cond-eq\` and \`cond-gte\` are the same FORM
   with a different key, so they share a stage and hang off it as \`refs\`.
   Distinct APIs — the nine hooks, the four providers — are not vocabulary and
   need a stage each.
3. **The step's content and its lab must show that feature and nothing else.**
   Use \`focus\` (an instrument scopes to one field) and \`panes\` (a spec lab
   opens only the tabs the feature is visible in).
4. **Every stage names its feature** through \`concept\` and/or \`ref\`/\`refs\`.
   \`bun run check:stages\` fails the build otherwise.

Coverage is measured against the project's own index: every concept in
\`lib/concepts\` and every entry in \`lib/reference\` carries \`step\`, naming the
lab that must teach it. **Never edit those \`step\` fields to close a gap** — that
moves the goalposts instead of writing the lesson.

## Done (${done.length}/${rows.length})

${done.map((r) => `- **${r.slug}** — ${r.stages} stages, ${r.want} features`).join('\n')}

## Outstanding (${todo.length})

| topic | stages | coverage | features never named by this lab |
|---|---|---|---|
${todo.map((r) => `| \`${r.slug}\` | ${r.stages} | ${r.pct}% of ${r.want} | ${r.missing.map((m) => `\`${m}\``).join(' ')} |`).join('\n')}

## Checks

\`\`\`bash
bun run check:stages      # every stage names a feature — gates the build
bun run audit:coverage    # per-topic coverage against concepts + reference
bun run type-check
\`\`\`
`;

mkdirSync('docs', { recursive: true });
writeFileSync('docs/STAGE-COVERAGE.md', body);
console.log(`docs/STAGE-COVERAGE.md: ${done.length} done, ${todo.length} outstanding`);
